project:
  type: website


website:
  favicon: "fish3.png"
  twitter-card: true
  title: "Palouse Anglers"
  navbar:
    tools:
      - icon: instagram
        href: https://instagram.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "More"
        menu:
        - maps.qmd
        - about.qmd
    
  


margin-header: |
  ![Logo image](/images/stonep.png)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



