project:
  type: website

website:
  title: "Palouse Anglers"
  favicon: "/images/fish3.png"
  twitter-card: true
  navbar:
    logo: "/images/stonep.png"
    left:
      - href: index.qmd
        text: Home
      - about.qmd


margin-header: |
  ![Logo image](/images/stonep.png)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



