project:
  type: website


website:
  favicon: "images/favicon.ico"
  twitter-card: true
  title: "Palouse Anglers"
  navbar:
    tools:
      - icon: instagram
        href: https://www.instagram.com/palouseanglers/
      - icon: github
        menu:
          - text: This Website
            url:  https://github.com/palouse-anglers/website
          - text: Suggestions/Bugs
            url:  https://github.com/palouse-anglers/website/issues
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Trip Planner"
        menu:
        - StJoe.qmd
        - NFClear.qmd
        - GrandeRonde.qmd
        - NFCDA.qmd
      - href: tying.qmd
        text: Tying
      - href: events.qmd
        text: Events
  
format:
  html:
    theme: 
       - cosmo
       - styles.scss
    css: styles.css
    toc: true



